sudo: required
services: docker
language: go
go: 1.x
env:
  - GO111MODULE=on
script:
  - go test
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o inkfish-linux-amd64
  - DOCKER_CONTENT_TRUST=1 docker build .
deploy:
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      tags: true
      repo: bsycorp/inkfish
  - provider: releases
    api_key:
      secure: CRJRFp+ycXLIuvJBr/XfbINFpzo62JWNtZvo+nZS1tYc/xakvlhDIR3pAYul9RLiKABB+/n0Y552hYP6kjoSiVUvcBm3vj5jw8Bk2WmWskBC9flzjTBtZAqxzI4I3jk8EJQYOK92/t/+ZZJKp89wew++79PWZUubO26ai9xZQgKgwy6MYqWHzbwdExIiDbYso6BlN6L4/6OiApWnT9B4kSx6Hsw6S4ZfBsLTfuO/d2Sge2KGVNHbgPpkDK6cWa9TmsgumaYVB7vamC9i3Q1Y5RIG7sDf8u1Q934rjVBmS5nbQmxJMQ0cWAmahj3M6irVbecQbXNVtNaJJY5C5+64JQ2AkYjoeOs/d6ggypoIXPt4m9Byo8xj30jnX69ecroao3nFLD9RvMbFAXW/QYWQINVe3BE85o4egByn9GyWLfCbYqg7PVXV0X8EqOrzo+eHXGLNLgwJZMC/f5qZKIfXi6NgKcpxBElrhg2gS4AsT+CDxmx20UHrsbId0y5+BKsdRmBspiL70qjUDfqY8ZLigp+IPGRd6kbgtzsrwHAeFoSzCOv7mFI9Q2E+incEsbddLFizjHuecGjT7odYAkYhDuwQ3eCxOi/TFlOBALE/IswKO0eQl4zhGd96TE4UWcndpFZ9ohuSbmcG0yA/wD/Dr3MXbeZc5FTA5a6FYAaZ5Fs=
    file: inkfish-linux-amd64
    on:
      tags: true
      repo: bsycorp/inkfish
