FROM golang:1.11 AS build-env
RUN useradd -u 10001 inkfish
WORKDIR /src

COPY go.mod go.sum /src/
RUN go mod download
ADD . /src
RUN make

FROM scratch
WORKDIR /
COPY --from=build-env /src/build/inkfish-linux /inkfish
COPY --from=build-env /etc/passwd /etc/passwd
USER inkfish

CMD ["/inkfish"]
