name: Build

on:
  create: # Triggers the workflow on new tag creation
    tags:
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish Image
      run: |
        echo ${{ secrets.DOCKERPASS }} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
        DOCKER_CONTENT_TRUST=1 docker build . -t bsycorp/inkfish:1.0.${{ github.run_number }}
        DOCKER_CONTENT_TRUST=1 docker build . -f Dockerfile-slim -t bsycorp/inkfish:1.0.${{ github.run_number }}-slim
        docker create --name built bsycorp/inkfish:1.0.${{ github.run_number }}
        docker cp built:/app/inkfish inkfish-linux-amd64
        bash ./scripts/docker-deploy.sh
    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: inkfish-linux-amd64
        path: inkfish-linux-amd64
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Asset
        uses: actions/download-artifact@v2
        with:
          name: inkfish-linux-amd64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: inkfish-linux-amd64
          asset_name: inkfish-linux-amd64
          asset_content_type: application/octet-stream